/******************************************************************************
*  Generated by PSoC Designer 5.4.3191
******************************************************************************/
#include <m8c.h>
// CSDSW18 address and mask defines
#pragma	ioport	CSDSW18_Data_ADDR:	0x0
BYTE			CSDSW18_Data_ADDR;
#pragma	ioport	CSDSW18_DriveMode_0_ADDR:	0x100
BYTE			CSDSW18_DriveMode_0_ADDR;
#pragma	ioport	CSDSW18_DriveMode_1_ADDR:	0x101
BYTE			CSDSW18_DriveMode_1_ADDR;
#pragma	ioport	CSDSW18_IntEn_ADDR:	0x1
BYTE			CSDSW18_IntEn_ADDR;
#define CSDSW18_MASK 0x1
#pragma	ioport	CSDSW18_MUXBusCtrl_ADDR:	0x1d8
BYTE			CSDSW18_MUXBusCtrl_ADDR;
// CSDSW18 Shadow defines
//   CSDSW18_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define CSDSW18_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
// CSDCapacitor address and mask defines
#pragma	ioport	CSDCapacitor_Data_ADDR:	0x0
BYTE			CSDCapacitor_Data_ADDR;
#pragma	ioport	CSDCapacitor_DriveMode_0_ADDR:	0x100
BYTE			CSDCapacitor_DriveMode_0_ADDR;
#pragma	ioport	CSDCapacitor_DriveMode_1_ADDR:	0x101
BYTE			CSDCapacitor_DriveMode_1_ADDR;
#pragma	ioport	CSDCapacitor_IntEn_ADDR:	0x1
BYTE			CSDCapacitor_IntEn_ADDR;
#define CSDCapacitor_MASK 0x2
#pragma	ioport	CSDCapacitor_MUXBusCtrl_ADDR:	0x1d8
BYTE			CSDCapacitor_MUXBusCtrl_ADDR;
// CSDCapacitor Shadow defines
//   CSDCapacitor_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define CSDCapacitor_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
// CSDSW17 address and mask defines
#pragma	ioport	CSDSW17_Data_ADDR:	0x0
BYTE			CSDSW17_Data_ADDR;
#pragma	ioport	CSDSW17_DriveMode_0_ADDR:	0x100
BYTE			CSDSW17_DriveMode_0_ADDR;
#pragma	ioport	CSDSW17_DriveMode_1_ADDR:	0x101
BYTE			CSDSW17_DriveMode_1_ADDR;
#pragma	ioport	CSDSW17_IntEn_ADDR:	0x1
BYTE			CSDSW17_IntEn_ADDR;
#define CSDSW17_MASK 0x4
#pragma	ioport	CSDSW17_MUXBusCtrl_ADDR:	0x1d8
BYTE			CSDSW17_MUXBusCtrl_ADDR;
// CSDSW17 Shadow defines
//   CSDSW17_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define CSDSW17_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
// CSDSW4 address and mask defines
#pragma	ioport	CSDSW4_Data_ADDR:	0x0
BYTE			CSDSW4_Data_ADDR;
#pragma	ioport	CSDSW4_DriveMode_0_ADDR:	0x100
BYTE			CSDSW4_DriveMode_0_ADDR;
#pragma	ioport	CSDSW4_DriveMode_1_ADDR:	0x101
BYTE			CSDSW4_DriveMode_1_ADDR;
#pragma	ioport	CSDSW4_IntEn_ADDR:	0x1
BYTE			CSDSW4_IntEn_ADDR;
#define CSDSW4_MASK 0x8
#pragma	ioport	CSDSW4_MUXBusCtrl_ADDR:	0x1d8
BYTE			CSDSW4_MUXBusCtrl_ADDR;
// CSDSW4 Shadow defines
//   CSDSW4_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define CSDSW4_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
// CSDSW16 address and mask defines
#pragma	ioport	CSDSW16_Data_ADDR:	0x0
BYTE			CSDSW16_Data_ADDR;
#pragma	ioport	CSDSW16_DriveMode_0_ADDR:	0x100
BYTE			CSDSW16_DriveMode_0_ADDR;
#pragma	ioport	CSDSW16_DriveMode_1_ADDR:	0x101
BYTE			CSDSW16_DriveMode_1_ADDR;
#pragma	ioport	CSDSW16_IntEn_ADDR:	0x1
BYTE			CSDSW16_IntEn_ADDR;
#define CSDSW16_MASK 0x10
#pragma	ioport	CSDSW16_MUXBusCtrl_ADDR:	0x1d8
BYTE			CSDSW16_MUXBusCtrl_ADDR;
// CSDSW16 Shadow defines
//   CSDSW16_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define CSDSW16_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
// CSDSW5 address and mask defines
#pragma	ioport	CSDSW5_Data_ADDR:	0x0
BYTE			CSDSW5_Data_ADDR;
#pragma	ioport	CSDSW5_DriveMode_0_ADDR:	0x100
BYTE			CSDSW5_DriveMode_0_ADDR;
#pragma	ioport	CSDSW5_DriveMode_1_ADDR:	0x101
BYTE			CSDSW5_DriveMode_1_ADDR;
#pragma	ioport	CSDSW5_IntEn_ADDR:	0x1
BYTE			CSDSW5_IntEn_ADDR;
#define CSDSW5_MASK 0x20
#pragma	ioport	CSDSW5_MUXBusCtrl_ADDR:	0x1d8
BYTE			CSDSW5_MUXBusCtrl_ADDR;
// CSDSW5 Shadow defines
//   CSDSW5_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define CSDSW5_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
// CSDSW15 address and mask defines
#pragma	ioport	CSDSW15_Data_ADDR:	0x0
BYTE			CSDSW15_Data_ADDR;
#pragma	ioport	CSDSW15_DriveMode_0_ADDR:	0x100
BYTE			CSDSW15_DriveMode_0_ADDR;
#pragma	ioport	CSDSW15_DriveMode_1_ADDR:	0x101
BYTE			CSDSW15_DriveMode_1_ADDR;
#pragma	ioport	CSDSW15_IntEn_ADDR:	0x1
BYTE			CSDSW15_IntEn_ADDR;
#define CSDSW15_MASK 0x40
#pragma	ioport	CSDSW15_MUXBusCtrl_ADDR:	0x1d8
BYTE			CSDSW15_MUXBusCtrl_ADDR;
// CSDSW15 Shadow defines
//   CSDSW15_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define CSDSW15_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
// CSDSW6 address and mask defines
#pragma	ioport	CSDSW6_Data_ADDR:	0x0
BYTE			CSDSW6_Data_ADDR;
#pragma	ioport	CSDSW6_DriveMode_0_ADDR:	0x100
BYTE			CSDSW6_DriveMode_0_ADDR;
#pragma	ioport	CSDSW6_DriveMode_1_ADDR:	0x101
BYTE			CSDSW6_DriveMode_1_ADDR;
#pragma	ioport	CSDSW6_IntEn_ADDR:	0x1
BYTE			CSDSW6_IntEn_ADDR;
#define CSDSW6_MASK 0x80
#pragma	ioport	CSDSW6_MUXBusCtrl_ADDR:	0x1d8
BYTE			CSDSW6_MUXBusCtrl_ADDR;
// CSDSW6 Shadow defines
//   CSDSW6_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define CSDSW6_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
// EzI2CsSDA address and mask defines
#pragma	ioport	EzI2CsSDA_Data_ADDR:	0x4
BYTE			EzI2CsSDA_Data_ADDR;
#pragma	ioport	EzI2CsSDA_DriveMode_0_ADDR:	0x104
BYTE			EzI2CsSDA_DriveMode_0_ADDR;
#pragma	ioport	EzI2CsSDA_DriveMode_1_ADDR:	0x105
BYTE			EzI2CsSDA_DriveMode_1_ADDR;
#pragma	ioport	EzI2CsSDA_IntEn_ADDR:	0x5
BYTE			EzI2CsSDA_IntEn_ADDR;
#define EzI2CsSDA_MASK 0x1
#pragma	ioport	EzI2CsSDA_MUXBusCtrl_ADDR:	0x1d9
BYTE			EzI2CsSDA_MUXBusCtrl_ADDR;
// EzI2CsSDA Shadow defines
//   EzI2CsSDA_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define EzI2CsSDA_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// EzI2CsSCL address and mask defines
#pragma	ioport	EzI2CsSCL_Data_ADDR:	0x4
BYTE			EzI2CsSCL_Data_ADDR;
#pragma	ioport	EzI2CsSCL_DriveMode_0_ADDR:	0x104
BYTE			EzI2CsSCL_DriveMode_0_ADDR;
#pragma	ioport	EzI2CsSCL_DriveMode_1_ADDR:	0x105
BYTE			EzI2CsSCL_DriveMode_1_ADDR;
#pragma	ioport	EzI2CsSCL_IntEn_ADDR:	0x5
BYTE			EzI2CsSCL_IntEn_ADDR;
#define EzI2CsSCL_MASK 0x2
#pragma	ioport	EzI2CsSCL_MUXBusCtrl_ADDR:	0x1d9
BYTE			EzI2CsSCL_MUXBusCtrl_ADDR;
// EzI2CsSCL Shadow defines
//   EzI2CsSCL_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define EzI2CsSCL_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// CSDSW29 address and mask defines
#pragma	ioport	CSDSW29_Data_ADDR:	0x4
BYTE			CSDSW29_Data_ADDR;
#pragma	ioport	CSDSW29_DriveMode_0_ADDR:	0x104
BYTE			CSDSW29_DriveMode_0_ADDR;
#pragma	ioport	CSDSW29_DriveMode_1_ADDR:	0x105
BYTE			CSDSW29_DriveMode_1_ADDR;
#pragma	ioport	CSDSW29_IntEn_ADDR:	0x5
BYTE			CSDSW29_IntEn_ADDR;
#define CSDSW29_MASK 0x8
#pragma	ioport	CSDSW29_MUXBusCtrl_ADDR:	0x1d9
BYTE			CSDSW29_MUXBusCtrl_ADDR;
// CSDSW29 Shadow defines
//   CSDSW29_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define CSDSW29_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// CSDSW7 address and mask defines
#pragma	ioport	CSDSW7_Data_ADDR:	0x4
BYTE			CSDSW7_Data_ADDR;
#pragma	ioport	CSDSW7_DriveMode_0_ADDR:	0x104
BYTE			CSDSW7_DriveMode_0_ADDR;
#pragma	ioport	CSDSW7_DriveMode_1_ADDR:	0x105
BYTE			CSDSW7_DriveMode_1_ADDR;
#pragma	ioport	CSDSW7_IntEn_ADDR:	0x5
BYTE			CSDSW7_IntEn_ADDR;
#define CSDSW7_MASK 0x20
#pragma	ioport	CSDSW7_MUXBusCtrl_ADDR:	0x1d9
BYTE			CSDSW7_MUXBusCtrl_ADDR;
// CSDSW7 Shadow defines
//   CSDSW7_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define CSDSW7_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// CSDSW28 address and mask defines
#pragma	ioport	CSDSW28_Data_ADDR:	0x4
BYTE			CSDSW28_Data_ADDR;
#pragma	ioport	CSDSW28_DriveMode_0_ADDR:	0x104
BYTE			CSDSW28_DriveMode_0_ADDR;
#pragma	ioport	CSDSW28_DriveMode_1_ADDR:	0x105
BYTE			CSDSW28_DriveMode_1_ADDR;
#pragma	ioport	CSDSW28_IntEn_ADDR:	0x5
BYTE			CSDSW28_IntEn_ADDR;
#define CSDSW28_MASK 0x80
#pragma	ioport	CSDSW28_MUXBusCtrl_ADDR:	0x1d9
BYTE			CSDSW28_MUXBusCtrl_ADDR;
// CSDSW28 Shadow defines
//   CSDSW28_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define CSDSW28_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// CSDSW8 address and mask defines
#pragma	ioport	CSDSW8_Data_ADDR:	0x8
BYTE			CSDSW8_Data_ADDR;
#pragma	ioport	CSDSW8_DriveMode_0_ADDR:	0x108
BYTE			CSDSW8_DriveMode_0_ADDR;
#pragma	ioport	CSDSW8_DriveMode_1_ADDR:	0x109
BYTE			CSDSW8_DriveMode_1_ADDR;
#pragma	ioport	CSDSW8_IntEn_ADDR:	0x9
BYTE			CSDSW8_IntEn_ADDR;
#define CSDSW8_MASK 0x1
#pragma	ioport	CSDSW8_MUXBusCtrl_ADDR:	0x1da
BYTE			CSDSW8_MUXBusCtrl_ADDR;
// CSDSW8 Shadow defines
//   CSDSW8_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define CSDSW8_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// CSDSW1 address and mask defines
#pragma	ioport	CSDSW1_Data_ADDR:	0x8
BYTE			CSDSW1_Data_ADDR;
#pragma	ioport	CSDSW1_DriveMode_0_ADDR:	0x108
BYTE			CSDSW1_DriveMode_0_ADDR;
#pragma	ioport	CSDSW1_DriveMode_1_ADDR:	0x109
BYTE			CSDSW1_DriveMode_1_ADDR;
#pragma	ioport	CSDSW1_IntEn_ADDR:	0x9
BYTE			CSDSW1_IntEn_ADDR;
#define CSDSW1_MASK 0x2
#pragma	ioport	CSDSW1_MUXBusCtrl_ADDR:	0x1da
BYTE			CSDSW1_MUXBusCtrl_ADDR;
// CSDSW1 Shadow defines
//   CSDSW1_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define CSDSW1_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// CSDSW21 address and mask defines
#pragma	ioport	CSDSW21_Data_ADDR:	0x8
BYTE			CSDSW21_Data_ADDR;
#pragma	ioport	CSDSW21_DriveMode_0_ADDR:	0x108
BYTE			CSDSW21_DriveMode_0_ADDR;
#pragma	ioport	CSDSW21_DriveMode_1_ADDR:	0x109
BYTE			CSDSW21_DriveMode_1_ADDR;
#pragma	ioport	CSDSW21_IntEn_ADDR:	0x9
BYTE			CSDSW21_IntEn_ADDR;
#define CSDSW21_MASK 0x4
#pragma	ioport	CSDSW21_MUXBusCtrl_ADDR:	0x1da
BYTE			CSDSW21_MUXBusCtrl_ADDR;
// CSDSW21 Shadow defines
//   CSDSW21_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define CSDSW21_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// CSDSW2 address and mask defines
#pragma	ioport	CSDSW2_Data_ADDR:	0x8
BYTE			CSDSW2_Data_ADDR;
#pragma	ioport	CSDSW2_DriveMode_0_ADDR:	0x108
BYTE			CSDSW2_DriveMode_0_ADDR;
#pragma	ioport	CSDSW2_DriveMode_1_ADDR:	0x109
BYTE			CSDSW2_DriveMode_1_ADDR;
#pragma	ioport	CSDSW2_IntEn_ADDR:	0x9
BYTE			CSDSW2_IntEn_ADDR;
#define CSDSW2_MASK 0x8
#pragma	ioport	CSDSW2_MUXBusCtrl_ADDR:	0x1da
BYTE			CSDSW2_MUXBusCtrl_ADDR;
// CSDSW2 Shadow defines
//   CSDSW2_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define CSDSW2_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// CSDSW20 address and mask defines
#pragma	ioport	CSDSW20_Data_ADDR:	0x8
BYTE			CSDSW20_Data_ADDR;
#pragma	ioport	CSDSW20_DriveMode_0_ADDR:	0x108
BYTE			CSDSW20_DriveMode_0_ADDR;
#pragma	ioport	CSDSW20_DriveMode_1_ADDR:	0x109
BYTE			CSDSW20_DriveMode_1_ADDR;
#pragma	ioport	CSDSW20_IntEn_ADDR:	0x9
BYTE			CSDSW20_IntEn_ADDR;
#define CSDSW20_MASK 0x10
#pragma	ioport	CSDSW20_MUXBusCtrl_ADDR:	0x1da
BYTE			CSDSW20_MUXBusCtrl_ADDR;
// CSDSW20 Shadow defines
//   CSDSW20_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define CSDSW20_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// CSDSW3 address and mask defines
#pragma	ioport	CSDSW3_Data_ADDR:	0x8
BYTE			CSDSW3_Data_ADDR;
#pragma	ioport	CSDSW3_DriveMode_0_ADDR:	0x108
BYTE			CSDSW3_DriveMode_0_ADDR;
#pragma	ioport	CSDSW3_DriveMode_1_ADDR:	0x109
BYTE			CSDSW3_DriveMode_1_ADDR;
#pragma	ioport	CSDSW3_IntEn_ADDR:	0x9
BYTE			CSDSW3_IntEn_ADDR;
#define CSDSW3_MASK 0x20
#pragma	ioport	CSDSW3_MUXBusCtrl_ADDR:	0x1da
BYTE			CSDSW3_MUXBusCtrl_ADDR;
// CSDSW3 Shadow defines
//   CSDSW3_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define CSDSW3_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// CSDSW19 address and mask defines
#pragma	ioport	CSDSW19_Data_ADDR:	0x8
BYTE			CSDSW19_Data_ADDR;
#pragma	ioport	CSDSW19_DriveMode_0_ADDR:	0x108
BYTE			CSDSW19_DriveMode_0_ADDR;
#pragma	ioport	CSDSW19_DriveMode_1_ADDR:	0x109
BYTE			CSDSW19_DriveMode_1_ADDR;
#pragma	ioport	CSDSW19_IntEn_ADDR:	0x9
BYTE			CSDSW19_IntEn_ADDR;
#define CSDSW19_MASK 0x40
#pragma	ioport	CSDSW19_MUXBusCtrl_ADDR:	0x1da
BYTE			CSDSW19_MUXBusCtrl_ADDR;
// CSDSW19 Shadow defines
//   CSDSW19_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define CSDSW19_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// CSDSW22 address and mask defines
#pragma	ioport	CSDSW22_Data_ADDR:	0x8
BYTE			CSDSW22_Data_ADDR;
#pragma	ioport	CSDSW22_DriveMode_0_ADDR:	0x108
BYTE			CSDSW22_DriveMode_0_ADDR;
#pragma	ioport	CSDSW22_DriveMode_1_ADDR:	0x109
BYTE			CSDSW22_DriveMode_1_ADDR;
#pragma	ioport	CSDSW22_IntEn_ADDR:	0x9
BYTE			CSDSW22_IntEn_ADDR;
#define CSDSW22_MASK 0x80
#pragma	ioport	CSDSW22_MUXBusCtrl_ADDR:	0x1da
BYTE			CSDSW22_MUXBusCtrl_ADDR;
// CSDSW22 Shadow defines
//   CSDSW22_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define CSDSW22_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// CSDSW14 address and mask defines
#pragma	ioport	CSDSW14_Data_ADDR:	0xc
BYTE			CSDSW14_Data_ADDR;
#pragma	ioport	CSDSW14_DriveMode_0_ADDR:	0x10c
BYTE			CSDSW14_DriveMode_0_ADDR;
#pragma	ioport	CSDSW14_DriveMode_1_ADDR:	0x10d
BYTE			CSDSW14_DriveMode_1_ADDR;
#pragma	ioport	CSDSW14_IntEn_ADDR:	0xd
BYTE			CSDSW14_IntEn_ADDR;
#define CSDSW14_MASK 0x1
#pragma	ioport	CSDSW14_MUXBusCtrl_ADDR:	0x1db
BYTE			CSDSW14_MUXBusCtrl_ADDR;
// CSDSW14 Shadow defines
//   CSDSW14_DataShadow define
extern BYTE Port_3_Data_SHADE;
#define CSDSW14_DataShadow (*(unsigned char*)&Port_3_Data_SHADE)
// CSDSW27 address and mask defines
#pragma	ioport	CSDSW27_Data_ADDR:	0xc
BYTE			CSDSW27_Data_ADDR;
#pragma	ioport	CSDSW27_DriveMode_0_ADDR:	0x10c
BYTE			CSDSW27_DriveMode_0_ADDR;
#pragma	ioport	CSDSW27_DriveMode_1_ADDR:	0x10d
BYTE			CSDSW27_DriveMode_1_ADDR;
#pragma	ioport	CSDSW27_IntEn_ADDR:	0xd
BYTE			CSDSW27_IntEn_ADDR;
#define CSDSW27_MASK 0x2
#pragma	ioport	CSDSW27_MUXBusCtrl_ADDR:	0x1db
BYTE			CSDSW27_MUXBusCtrl_ADDR;
// CSDSW27 Shadow defines
//   CSDSW27_DataShadow define
extern BYTE Port_3_Data_SHADE;
#define CSDSW27_DataShadow (*(unsigned char*)&Port_3_Data_SHADE)
// CSDSW13 address and mask defines
#pragma	ioport	CSDSW13_Data_ADDR:	0xc
BYTE			CSDSW13_Data_ADDR;
#pragma	ioport	CSDSW13_DriveMode_0_ADDR:	0x10c
BYTE			CSDSW13_DriveMode_0_ADDR;
#pragma	ioport	CSDSW13_DriveMode_1_ADDR:	0x10d
BYTE			CSDSW13_DriveMode_1_ADDR;
#pragma	ioport	CSDSW13_IntEn_ADDR:	0xd
BYTE			CSDSW13_IntEn_ADDR;
#define CSDSW13_MASK 0x4
#pragma	ioport	CSDSW13_MUXBusCtrl_ADDR:	0x1db
BYTE			CSDSW13_MUXBusCtrl_ADDR;
// CSDSW13 Shadow defines
//   CSDSW13_DataShadow define
extern BYTE Port_3_Data_SHADE;
#define CSDSW13_DataShadow (*(unsigned char*)&Port_3_Data_SHADE)
// CSDSW26 address and mask defines
#pragma	ioport	CSDSW26_Data_ADDR:	0xc
BYTE			CSDSW26_Data_ADDR;
#pragma	ioport	CSDSW26_DriveMode_0_ADDR:	0x10c
BYTE			CSDSW26_DriveMode_0_ADDR;
#pragma	ioport	CSDSW26_DriveMode_1_ADDR:	0x10d
BYTE			CSDSW26_DriveMode_1_ADDR;
#pragma	ioport	CSDSW26_IntEn_ADDR:	0xd
BYTE			CSDSW26_IntEn_ADDR;
#define CSDSW26_MASK 0x8
#pragma	ioport	CSDSW26_MUXBusCtrl_ADDR:	0x1db
BYTE			CSDSW26_MUXBusCtrl_ADDR;
// CSDSW26 Shadow defines
//   CSDSW26_DataShadow define
extern BYTE Port_3_Data_SHADE;
#define CSDSW26_DataShadow (*(unsigned char*)&Port_3_Data_SHADE)
// CSDSW12 address and mask defines
#pragma	ioport	CSDSW12_Data_ADDR:	0xc
BYTE			CSDSW12_Data_ADDR;
#pragma	ioport	CSDSW12_DriveMode_0_ADDR:	0x10c
BYTE			CSDSW12_DriveMode_0_ADDR;
#pragma	ioport	CSDSW12_DriveMode_1_ADDR:	0x10d
BYTE			CSDSW12_DriveMode_1_ADDR;
#pragma	ioport	CSDSW12_IntEn_ADDR:	0xd
BYTE			CSDSW12_IntEn_ADDR;
#define CSDSW12_MASK 0x10
#pragma	ioport	CSDSW12_MUXBusCtrl_ADDR:	0x1db
BYTE			CSDSW12_MUXBusCtrl_ADDR;
// CSDSW12 Shadow defines
//   CSDSW12_DataShadow define
extern BYTE Port_3_Data_SHADE;
#define CSDSW12_DataShadow (*(unsigned char*)&Port_3_Data_SHADE)
// CSDSW25 address and mask defines
#pragma	ioport	CSDSW25_Data_ADDR:	0xc
BYTE			CSDSW25_Data_ADDR;
#pragma	ioport	CSDSW25_DriveMode_0_ADDR:	0x10c
BYTE			CSDSW25_DriveMode_0_ADDR;
#pragma	ioport	CSDSW25_DriveMode_1_ADDR:	0x10d
BYTE			CSDSW25_DriveMode_1_ADDR;
#pragma	ioport	CSDSW25_IntEn_ADDR:	0xd
BYTE			CSDSW25_IntEn_ADDR;
#define CSDSW25_MASK 0x20
#pragma	ioport	CSDSW25_MUXBusCtrl_ADDR:	0x1db
BYTE			CSDSW25_MUXBusCtrl_ADDR;
// CSDSW25 Shadow defines
//   CSDSW25_DataShadow define
extern BYTE Port_3_Data_SHADE;
#define CSDSW25_DataShadow (*(unsigned char*)&Port_3_Data_SHADE)
// CSDSW11 address and mask defines
#pragma	ioport	CSDSW11_Data_ADDR:	0xc
BYTE			CSDSW11_Data_ADDR;
#pragma	ioport	CSDSW11_DriveMode_0_ADDR:	0x10c
BYTE			CSDSW11_DriveMode_0_ADDR;
#pragma	ioport	CSDSW11_DriveMode_1_ADDR:	0x10d
BYTE			CSDSW11_DriveMode_1_ADDR;
#pragma	ioport	CSDSW11_IntEn_ADDR:	0xd
BYTE			CSDSW11_IntEn_ADDR;
#define CSDSW11_MASK 0x40
#pragma	ioport	CSDSW11_MUXBusCtrl_ADDR:	0x1db
BYTE			CSDSW11_MUXBusCtrl_ADDR;
// CSDSW11 Shadow defines
//   CSDSW11_DataShadow define
extern BYTE Port_3_Data_SHADE;
#define CSDSW11_DataShadow (*(unsigned char*)&Port_3_Data_SHADE)
// CSDSW24 address and mask defines
#pragma	ioport	CSDSW24_Data_ADDR:	0xc
BYTE			CSDSW24_Data_ADDR;
#pragma	ioport	CSDSW24_DriveMode_0_ADDR:	0x10c
BYTE			CSDSW24_DriveMode_0_ADDR;
#pragma	ioport	CSDSW24_DriveMode_1_ADDR:	0x10d
BYTE			CSDSW24_DriveMode_1_ADDR;
#pragma	ioport	CSDSW24_IntEn_ADDR:	0xd
BYTE			CSDSW24_IntEn_ADDR;
#define CSDSW24_MASK 0x80
#pragma	ioport	CSDSW24_MUXBusCtrl_ADDR:	0x1db
BYTE			CSDSW24_MUXBusCtrl_ADDR;
// CSDSW24 Shadow defines
//   CSDSW24_DataShadow define
extern BYTE Port_3_Data_SHADE;
#define CSDSW24_DataShadow (*(unsigned char*)&Port_3_Data_SHADE)
// CSDSW10 address and mask defines
#pragma	ioport	CSDSW10_Data_ADDR:	0x10
BYTE			CSDSW10_Data_ADDR;
#pragma	ioport	CSDSW10_DriveMode_0_ADDR:	0x110
BYTE			CSDSW10_DriveMode_0_ADDR;
#pragma	ioport	CSDSW10_DriveMode_1_ADDR:	0x111
BYTE			CSDSW10_DriveMode_1_ADDR;
#pragma	ioport	CSDSW10_IntEn_ADDR:	0x11
BYTE			CSDSW10_IntEn_ADDR;
#define CSDSW10_MASK 0x1
#pragma	ioport	CSDSW10_MUXBusCtrl_ADDR:	0x1df
BYTE			CSDSW10_MUXBusCtrl_ADDR;
// CSDSW10 Shadow defines
//   CSDSW10_DataShadow define
extern BYTE Port_4_Data_SHADE;
#define CSDSW10_DataShadow (*(unsigned char*)&Port_4_Data_SHADE)
// CSDSW23 address and mask defines
#pragma	ioport	CSDSW23_Data_ADDR:	0x10
BYTE			CSDSW23_Data_ADDR;
#pragma	ioport	CSDSW23_DriveMode_0_ADDR:	0x110
BYTE			CSDSW23_DriveMode_0_ADDR;
#pragma	ioport	CSDSW23_DriveMode_1_ADDR:	0x111
BYTE			CSDSW23_DriveMode_1_ADDR;
#pragma	ioport	CSDSW23_IntEn_ADDR:	0x11
BYTE			CSDSW23_IntEn_ADDR;
#define CSDSW23_MASK 0x2
#pragma	ioport	CSDSW23_MUXBusCtrl_ADDR:	0x1df
BYTE			CSDSW23_MUXBusCtrl_ADDR;
// CSDSW23 Shadow defines
//   CSDSW23_DataShadow define
extern BYTE Port_4_Data_SHADE;
#define CSDSW23_DataShadow (*(unsigned char*)&Port_4_Data_SHADE)
// CSDSW9 address and mask defines
#pragma	ioport	CSDSW9_Data_ADDR:	0x10
BYTE			CSDSW9_Data_ADDR;
#pragma	ioport	CSDSW9_DriveMode_0_ADDR:	0x110
BYTE			CSDSW9_DriveMode_0_ADDR;
#pragma	ioport	CSDSW9_DriveMode_1_ADDR:	0x111
BYTE			CSDSW9_DriveMode_1_ADDR;
#pragma	ioport	CSDSW9_IntEn_ADDR:	0x11
BYTE			CSDSW9_IntEn_ADDR;
#define CSDSW9_MASK 0x4
#pragma	ioport	CSDSW9_MUXBusCtrl_ADDR:	0x1df
BYTE			CSDSW9_MUXBusCtrl_ADDR;
// CSDSW9 Shadow defines
//   CSDSW9_DataShadow define
extern BYTE Port_4_Data_SHADE;
#define CSDSW9_DataShadow (*(unsigned char*)&Port_4_Data_SHADE)
// CSDSW0 address and mask defines
#pragma	ioport	CSDSW0_Data_ADDR:	0x10
BYTE			CSDSW0_Data_ADDR;
#pragma	ioport	CSDSW0_DriveMode_0_ADDR:	0x110
BYTE			CSDSW0_DriveMode_0_ADDR;
#pragma	ioport	CSDSW0_DriveMode_1_ADDR:	0x111
BYTE			CSDSW0_DriveMode_1_ADDR;
#pragma	ioport	CSDSW0_IntEn_ADDR:	0x11
BYTE			CSDSW0_IntEn_ADDR;
#define CSDSW0_MASK 0x8
#pragma	ioport	CSDSW0_MUXBusCtrl_ADDR:	0x1df
BYTE			CSDSW0_MUXBusCtrl_ADDR;
// CSDSW0 Shadow defines
//   CSDSW0_DataShadow define
extern BYTE Port_4_Data_SHADE;
#define CSDSW0_DataShadow (*(unsigned char*)&Port_4_Data_SHADE)
