/******************************************************************************
*  Generated by PSoC Designer 5.3.2710
******************************************************************************/
//=============================================================================
//  FILENAME:   GlobalParams.h
//  DATE:       31 January 2006
//
//  DESCRIPTION:
//  Constants describing many of the global parameter settings.
//  This file contains defines to support register initialization
//  for the CY8C20636AN
//
//  Copyright (c) Cypress Semiconductor 2012. All Rights Reserved.
//
// NOTES:
// Do not modify this file. It is generated by PSoC Designer each time the
// generate application function is run. The values of the parameters in this
// file can be modified by changing the values of the global parameters in the
// device editor.
//=============================================================================
//

#define IMO_SETTING            0x2     //Power Setting 

#define CPU_CLOCK              0x3     //CPU clock value
#define CPU_CLOCK_MASK         0x7     //CPU clock mask
#define CPU_CLOCK_JUST         0x3     //CPU clock value justified

#define SLEEP_TIMER            0x0     //Sleep Timer value
#define SLEEP_TIMER_MASK       0x18    //Sleep Timer mask
#define SLEEP_TIMER_JUST       0x0     //Sleep Timer value justified

#define SYSCLK_SOURCE          (0x0 | 0x0) // SysClk Source setting
#define SYSCLK_SOURCE_MASK     (0x4 | 0x2) // SysClk Source setting mask
#define SYSCLK_SOURCE_JUST     (0x0 | 0x0) // SysClk Source setting justified

#define TRIP_VOLTAGE           0x7     //Trip Voltage
#define TRIP_VOLTAGE_MASK      0x7     //Trip Voltage mask
#define TRIP_VOLTAGE_JUST      0x7     //Trip Voltage justified

#define LVD_TBEN               0x0     //LVDThrottleBack value
#define LVD_TBEN_MASK          0x8     //LVDThrottleBack mask
#define LVD_TBEN_JUST          0x0     //LVDThrottleBack value justified

#define WATCHDOG_ENABLE        0x0     //Watchdog Enable 1 = Enable
#define INTERRUPT_MODE         0x0     //Interrupt Mode, 0 = Low, 1 = ChangeFromRead

#define P1_0_DATA_OUTPUT       (0x0 | 0x0)   // P1[0] Data Output setting
#define P1_0_DATA_OUTPUT_MASK  (0x2 | 0x1)   // P1[0] Data Output setting mask
#define P1_0_DATA_OUTPUT_JUST  (0x0 | 0x0)   // P1[0] Data Output setting justified

#define P1_2_DATA_OUTPUT       (0x0 | 0x0)   // P1[2] Data Output setting
#define P1_2_DATA_OUTPUT_MASK  (0x8 | 0x4)   // P1[2] Data Output setting mask
#define P1_2_DATA_OUTPUT_JUST  (0x0 | 0x0)   // P1[2] Data Output setting justified

#define P1_4_DATA_OUTPUT       (0x0 | 0x0)   // P1[4] Data Output setting
#define P1_4_DATA_OUTPUT_MASK  (0x20 | 0x10) // P1[4] Data Output setting mask
#define P1_4_DATA_OUTPUT_JUST  (0x0 | 0x0)   // P1[4] Data Output setting justified

#define P1_6_DATA_OUTPUT       (0x0 | 0x0)   // P1[6] Data Output setting
#define P1_6_DATA_OUTPUT_MASK  (0x80 | 0x40) // P1[6] Data Output setting mask
#define P1_6_DATA_OUTPUT_JUST  (0x0 | 0x0)   // P1[6] Data Output setting justified

#define POR_LEVEL              (0x0 | 0x0) // POR setting
#define POR_LEVEL_MASK         (0x80 | 0x30) // POR setting mask
#define POR_LEVEL_JUST         (0x0 | 0x0) // POR setting justified

#define ILO_SETTING:           0x0     // ILO frequecy
#define ILO_SETTING_MASK:      0x20    // ILO frequecy mask
#define ILO_SETTING_JUST:      0x0     // ILO frequecy justified

#define SELECT_32K             0x0     //32K select value
#define SELECT_32K_MASK        0x80    //32K select mask
#define SELECT_32K_JUST        0x0     //32K select value justified

//
// register initial values
//

//#define ANALOG_IO_CONTROL    0x@AnalogIOControl_0_DATA //Analog IO Control register (ABF_CR)

#define PORT_0_DRIVE_0         0x0     //Port 0 drive mode 0 register (PRT0DM0)
#define PORT_0_DRIVE_1         0xff    //Port 0 drive mode 1 register (PRT0DM1)
#define PORT_0_INTENABLE       0x0     //Port 0 interrupt enable register (PRT0IE)

#define PORT_1_DRIVE_0         0x3     //Port 1 drive mode 0 register (PRT1DM0)
#define PORT_1_DRIVE_1         0xab    //Port 1 drive mode 1 register (PRT1DM1)
#define PORT_1_INTENABLE       0x0     //Port 1 interrupt enable register (PRT1IE)

#define PORT_2_DRIVE_0         0x0     //Port 2 drive mode 0 register (PRT2DM0)
#define PORT_2_DRIVE_1         0xff    //Port 2 drive mode 1 register (PRT2DM1)
#define PORT_2_INTENABLE       0x0     //Port 2 interrupt enable register (PRT2IE)

#define PORT_3_DRIVE_0         0x0     //Port 3 drive mode 0 register (PRT3DM0)
#define PORT_3_DRIVE_1         0xff    //Port 3 drive mode 1 register (PRT3DM1)
#define PORT_3_INTENABLE       0x0     //Port 3 interrupt enable register (PRT3IE)

#define PORT_4_DRIVE_0         0x0     //Port 4 drive mode 0 register (PRT4DM0)
#define PORT_4_DRIVE_1         0xf     //Port 4 drive mode 1 register (PRT4DM1)
#define PORT_4_INTENABLE       0x0     //Port 4 interrupt enable register (PRT4IE)

// end of file GlobalParams.h
